# Generated by Django 4.1.3 on 2022-11-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField(max_length=3)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('fecha_de_nacimiento', models.DateField(max_length=50)),
            ],
        ),
    ]
